-- Database schema for Ultimate Character Generator (MariaDB)
-- Generated by automation - includes taxonomy, computed keys, rules, and admin tables

CREATE TABLE IF NOT EXISTS species (
    id INT AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    is_active TINYINT(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ancestry_group (
    id INT AUTO_INCREMENT PRIMARY KEY,
    species_id INT NOT NULL,
    slug VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    parent_id INT NULL,
    include_children TINYINT(1) DEFAULT 1,
    is_active TINYINT(1) DEFAULT 1,
    UNIQUE KEY uniq_species_slug (species_id, slug),
    CONSTRAINT fk_ancestry_species FOREIGN KEY (species_id) REFERENCES species(id) ON DELETE CASCADE,
    CONSTRAINT fk_ancestry_parent FOREIGN KEY (parent_id) REFERENCES ancestry_group(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS gender (
    id INT AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS life_stage (
    id INT AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    sort_order INT DEFAULT 0,
    is_active TINYINT(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stage_modifier (
    id INT AUTO_INCREMENT PRIMARY KEY,
    life_stage_id INT NOT NULL,
    `key` VARCHAR(128) NOT NULL,
    value_json JSON NOT NULL,
    CONSTRAINT fk_stage_modifier FOREIGN KEY (life_stage_id) REFERENCES life_stage(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS computed_key (
    id INT AUTO_INCREMENT PRIMARY KEY,
    key_path VARCHAR(255) NOT NULL UNIQUE,
    label VARCHAR(255) NOT NULL,
    unit VARCHAR(32),
    category VARCHAR(64),
    description TEXT,
    is_active TINYINT(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rule (
    id INT AUTO_INCREMENT PRIMARY KEY,
    computed_key_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    priority INT DEFAULT 100,
    is_active TINYINT(1) DEFAULT 1,
    distribution ENUM('gaussian','uniform','linear','ratio','piecewise','sigmoid','choice') NOT NULL,
    params_json JSON NOT NULL,
    notes TEXT,
    CONSTRAINT fk_rule_computed_key FOREIGN KEY (computed_key_id) REFERENCES computed_key(id) ON DELETE CASCADE,
    KEY idx_rule_priority (computed_key_id, priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rule_condition (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rule_id INT NOT NULL,
    species_id INT NULL,
    ancestry_group_id INT NULL,
    include_children TINYINT(1) DEFAULT 1,
    gender_id INT NULL,
    life_stage_id INT NULL,
    min_age INT NULL,
    max_age INT NULL,
    CONSTRAINT fk_rule_condition_rule FOREIGN KEY (rule_id) REFERENCES rule(id) ON DELETE CASCADE,
    CONSTRAINT fk_rule_condition_species FOREIGN KEY (species_id) REFERENCES species(id) ON DELETE CASCADE,
    CONSTRAINT fk_rule_condition_ancestry FOREIGN KEY (ancestry_group_id) REFERENCES ancestry_group(id) ON DELETE SET NULL,
    CONSTRAINT fk_rule_condition_gender FOREIGN KEY (gender_id) REFERENCES gender(id) ON DELETE CASCADE,
    CONSTRAINT fk_rule_condition_life_stage FOREIGN KEY (life_stage_id) REFERENCES life_stage(id) ON DELETE CASCADE,
    KEY idx_condition_rule (rule_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rule_dependency (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rule_id INT NOT NULL,
    depends_on_computed_key_id INT NOT NULL,
    CONSTRAINT fk_rule_dep_rule FOREIGN KEY (rule_id) REFERENCES rule(id) ON DELETE CASCADE,
    CONSTRAINT fk_rule_dep_key FOREIGN KEY (depends_on_computed_key_id) REFERENCES computed_key(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS base_profile (
    id INT AUTO_INCREMENT PRIMARY KEY,
    species_id INT NULL,
    ancestry_group_id INT NULL,
    include_children TINYINT(1) DEFAULT 1,
    gender_id INT NULL,
    life_stage_id INT NULL,
    priority INT DEFAULT 100,
    profile_json JSON NOT NULL,
    CONSTRAINT fk_base_profile_species FOREIGN KEY (species_id) REFERENCES species(id) ON DELETE CASCADE,
    CONSTRAINT fk_base_profile_ancestry FOREIGN KEY (ancestry_group_id) REFERENCES ancestry_group(id) ON DELETE SET NULL,
    CONSTRAINT fk_base_profile_gender FOREIGN KEY (gender_id) REFERENCES gender(id) ON DELETE CASCADE,
    CONSTRAINT fk_base_profile_life_stage FOREIGN KEY (life_stage_id) REFERENCES life_stage(id) ON DELETE CASCADE,
    KEY idx_base_profile_priority (priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) DEFAULT 'admin',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    admin_user_id INT NULL,
    action VARCHAR(128) NOT NULL,
    entity VARCHAR(128) NOT NULL,
    entity_id INT NULL,
    payload_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_user FOREIGN KEY (admin_user_id) REFERENCES admin_user(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Index to quickly fetch computed keys for dependencies
DROP INDEX IF EXISTS idx_computed_key_category ON computed_key;
CREATE INDEX idx_computed_key_category ON computed_key(category);
